In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
import math

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
d1=pd.read_csv('/content/drive/MyDrive/datasets/vehicles.csv')
d1.head()

,id,url,region,region_url,price,year,manufacturer,model,condition,cylinders,...,size,type,paint_color,image_url,description,county,state,lat,long,posting_date
0,7222695916,https://prescott.craigslist.org/cto/d/prescott...,prescott,https://prescott.craigslist.org,6000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,az,NaN,NaN,NaN
1,7218891961,https://fayar.craigslist.org/ctd/d/bentonville...,fayetteville,https://fayar.craigslist.org,11900,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,ar,NaN,NaN,NaN
2,7221797935,https://keys.craigslist.org/cto/d/summerland-k...,florida keys,https://keys.craigslist.org,21000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,fl,NaN,NaN,NaN
3,7222270760,https://worcester.craigslist.org/cto/d/west-br...,worcester / central MA,https://worcester.craigslist.org,1500,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,ma,NaN,NaN,NaN
4,7210384030,https://greensboro.craigslist.org/cto/d/trinit...,greensboro,https://greensboro.craigslist.org,4900,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,nc,NaN,NaN,NaN

In [4]:
d1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 426880 entries, 0 to 426879
Data columns (total 26 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            426880 non-null  int64
 1   url           426880 non-null  object
 2   region        426880 non-null  object
 3   region_url    426880 non-null  object
 4   price         426880 non-null  int64
 5   year          425675 non-null  float64
 6   manufacturer  409234 non-null  object
 7   model         421603 non-null  object
 8   condition     252776 non-null  object
 9   cylinders     249202 non-null  object
 10  fuel          423867 non-null  object
 11  odometer      422480 non-null  float64
 12  title_status  418638 non-null  object
 13  transmission  424324 non-null  object
 14  VIN           265838 non-null  object
 15  drive         296313 non-null  object
 16  size          120519 non-null  object
 17  type          334022 non-null  object
 18  paint_color   296677 non-null  object
 19  image_url     426812 non-null  object
 20  description   426810 non-null  object
 21  county        0 non-null       float64
 22  state         426880 non-null  object
 23  lat           420331 non-null  float64
 24  long          420331 non-null  float64
 25  posting_date  426812 non-null  object
dtypes: float64(5), int64(2), object(19)
memory usage: 84.7+ MB

In [5]:
drop_columns = ['url', 'region', 'region_url', 'VIN', 'size','image_url','county','state','lat','long','posting_date','description']
d1 = d1.drop(columns = drop_columns)

In [ ]:
d1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 115988 entries, 31 to 426878
Data columns (total 14 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            115988 non-null  int64
 1   price         115988 non-null  int64
 2   year          115988 non-null  float64
 3   manufacturer  115988 non-null  object
 4   model         115988 non-null  object
 5   condition     115988 non-null  object
 6   cylinders     115988 non-null  object
 7   fuel          115988 non-null  object
 8   odometer      115988 non-null  float64
 9   title_status  115988 non-null  object
 10  transmission  115988 non-null  object
 11  drive         115988 non-null  object
 12  type          115988 non-null  object
 13  paint_color   115988 non-null  object
dtypes: float64(2), int64(2), object(10)
memory usage: 13.3+ MB

In [7]:
d1.head()

,id,price,year,manufacturer,model,condition,cylinders,fuel,odometer,title_status,transmission,drive,type,paint_color
0,35,13152,114,31,20664,4,7,4,104870,3,2,2,6,6
1,22,861,114,31,20664,4,7,4,104870,3,2,2,6,6
2,30,5021,114,31,20664,4,7,4,104870,3,2,2,6,6
3,33,2370,114,31,20664,4,7,4,104870,3,2,2,6,6
4,5,11921,114,31,20664,4,7,4,104870,3,2,2,6,6

In [6]:
from sklearn.preprocessing import LabelEncoder
for col in d1.columns:
      le = LabelEncoder()
      le.fit(list(d1[col].astype(str).values))
      d1[col] = le.transform(list(d1[col].astype(str).values))

In [ ]:
d1.head()

   id  price  year  manufacturer  ...  transmission  drive  type  paint_color
0  35  13152   114            31  ...             2      2     6            6
1  22    861   114            31  ...             2      2     6            6
2  30   5021   114            31  ...             2      2     6            6
3  33   2370   114            31  ...             2      2     6            6
4   5  11921   114            31  ...             2      2     6            6

[5 rows x 14 columns]

In [8]:
year_data = d1['year']


price_data = d1['price']

odometer_data=d1['odometer']

#year = np.array(year_data).reshape(-1,1)

price = np.array(price_data).reshape(-1,1)
#odometer = np.array(odometer_data).reshape(-1,1)
features=np.array([year_data,odometer_data]).T

In [9]:
model = LinearRegression()
model.fit(features,price)

LinearRegression()

In [10]:
result=model.predict([[113,104870]])
print(result)
d1.info()

[[6161.03194768]]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 426880 entries, 0 to 426879
Data columns (total 14 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            426880 non-null  int64
 1   price         426880 non-null  int64
 2   year          426880 non-null  int64
 3   manufacturer  426880 non-null  int64
 4   model         426880 non-null  int64
 5   condition     426880 non-null  int64
 6   cylinders     426880 non-null  int64
 7   fuel          426880 non-null  int64
 8   odometer      426880 non-null  int64
 9   title_status  426880 non-null  int64
 10  transmission  426880 non-null  int64
 11  drive         426880 non-null  int64
 12  type          426880 non-null  int64
 13  paint_color   426880 non-null  int64
dtypes: int64(14)
memory usage: 45.6 MB

In [12]:
x=d1.drop('price',axis=1)
y=d1['price']

In [14]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

In [16]:
logre = LinearRegression()
logre.fit(x_train,y_train)

LinearRegression()

In [20]:
from sklearn.metrics import accuracy_score
y_pred = logre.predict(x_test)
print(y_pred)

[7557.34131225 7357.36992525 6743.39003635 ... 9725.25757879 8544.80905998
 8434.68814253]